# Generated by Django 4.2.13 on 2024-06-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='resopitory',
            new_name='repository',
        ),
    ]
